### ISSUE TITLE
GPIO initialization overwrites current value

### ISSUE THREAD

**Issue by vesley** [vsergeev/lua-periphery#13]
I'm using GPIO periphery with a nginx web server (to power on/off some electrical devices).
I want to read and display the current status (on/off) on the web page.
But each time I open a gpio pin to read the current value the value is set to 0 (false) on initialization.

``` lua
local gpio = require('periphery').GPIO
-- The next line resets the value of pin 12 to false (even if it was previously set to true)
local gpio_out = gpio(12, "out")
local value = gpio_out:read()
print(value)
gpio_out:write(not value)
gpio_out:close()
os.exit()
```

If you call the program twice (or multiple times) you will see that the value of pin 12 is always false.
Is it possible to open a pin without initializing/overwriting a previously set value?

**Comment by vsergeev** [comment]
Thanks for your issue. This is definitely an important use case.

I've released a new version of lua-periphery that adds support for preserving the direction when opening GPIOs. You can now specify the `"preserve"` direction or omit it altogether when opening a GPIO, and it will retain the existing direction:

``` lua
local periphery = require('periphery')

local gpio12 = periphery.GPIO(12, 'preserve')
-- or just
local gpio12 = periphery.GPIO(12)
```
