### ISSUE TITLE
Lacking PWM feature

### ISSUE THREAD

**Issue by gustavohmsilva** [vsergeev/lua-periphery#19]
I've noticed that although the Python version has PWM capabilities, the Lua version don't count with it. Is this due to some limitation in the Language or just wasn't implemented? If so, is this something on a future milestone?

**Comment by vsergeev** [comment]
No limitations -- the PWM and LED modules in python-periphery were user contributions. They can be added to c-periphery down the line (or sooner with a PR!), and then easily bound to lua-periphery.

I think I'll create issues here linked to c-periphery issues for each of the modules missing from c-periphery/lua-periphery, but present in python-periphery. It would be nice to have consistent support and API across all three.

**Comment by Janaka-Steph** [comment]
Sorry to reopen this issue, but I am also interested by this feature. Where can I follow the development? Any other recommendation to have PWM in Lua on Raspberry?

**Comment by vsergeev** [comment]
I'm actually planning on implementing LED and PWM support in both c-periphery and lua-periphery in the coming 1.5 weeks, so there will be a v2.1.0 release of both soon.

I'm not aware of other Lua libraries with PWM support, but you could access the `/sys/class/pwm` files directly with the built-in `io` library in the meanwhile.

**Comment by Janaka-Steph** [comment]
Ok great, thank you for your detailed answer.

**Comment by vsergeev** [comment]
@Janaka-Steph I just released v2.1.0 of c-periphery and lua-periphery with LED and PWM support.

**Comment by Janaka-Steph** [comment]
Woohooo thank you!!
