### ISSUE TITLE
how to send hex data with serial?

### ISSUE THREAD

**Issue by YoonesImani** [vsergeev/lua-periphery#25]
Hi, how can I send serial data in HEX format?

Thanks

**Comment by vsergeev** [comment]
This is a bit vague. Do you want to send binary data? or binary data encoded into an ASCII hex string?

**Comment by YoonesImani** [comment]
actually, I want to send binary data.

**Comment by vsergeev** [comment]
Lua strings can contain binary data, so you can write binary data with the `write()` method on the serial handle (https://github.com/vsergeev/lua-periphery/blob/master/docs/serial.md).

**Comment by YoonesImani** [comment]
The problem is for example when I want to send \r (carriage return) it
sends two characters "\" and "r"

**Comment by vsergeev** [comment]
I think your problem is somewhere in the byte string construction.

The Lua string "\r" is one byte:

```
Lua 5.4.0  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> s = "\r"
> #s
1
> s == "\x0d"
true
> string.byte(s, 1) == 0x0d
true
> 
```
