### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by ItssBrunoo** [vsergeev/lua-periphery#28]
This what i have:
function setUniform(job, playerPed)
	TriggerEvent('skinchanger:getSkin', function(skin)
		if skin.sex == 0 then
			if Config.Uniforms[job].male ~= nil then
				TriggerEvent('skinchanger:loadClothes', skin, Config.Uniforms[job].male)
			else
				ESX.ShowNotification(_U('no_outfit'))
			end

			if job == 'bullet_wear' or job == 'fardacoletea_wear' or job == 'fardacoleteb_wear' or  job == 'fardagoea_wear' or job == 'fardagoeb_wear' then
				SetPedArmour(playerPed, 100)
			end
		else
			if Config.Uniforms[job].female ~= nil then
				TriggerEvent('skinchanger:loadClothes', skin, Config.Uniforms[job].female)
			else
				ESX.ShowNotification(_U('no_outfit'))
			end

			if job == 'bullet_wear' or job == 'fardacoletea_wear' or job == 'fardacoleteb_wear' or  job == 'fardagoea_wear' or job == 'fardagoeb_wear' then
				SetPedArmour(playerPed, 100)
			end
		end
	end)
end
And this is the error
![dadawda](https://github.com/vsergeev/lua-periphery/assets/139887985/6f5eecbd-7e4c-48e7-8496-89227b13b194)

**Comment by vsergeev** [comment]
What does this have to do with lua-periphery?
