### ISSUE TITLE
Lua5.3: undefined symbol: luaL_checkunsigned

### ISSUE THREAD

**Issue by Desertification** [vsergeev/lua-periphery#3]
When running "require('periphery')" i get the following error message:

```
error loading module 'periphery' from file '/usr/local/lib/lua/5.3/periphery.so'
        /usr/local/lib/lua/5.3/periphery.so: undefined symbol: luaL_checkunsigned
stack traceback:
        [C]: in ?
        [C]: in function 'require'
        stdin:1: in main chunk
        [C]: in ?
```

I am using a raspberry pi running rasbian and Lua 5.3.0.
Periphery is installed with luarocks.
When running the instruction from Lua 5.2.4, I get no errors.

**Comment by vsergeev** [comment]
Thanks for the report. Lua 5.3 support added in b54e56c91dad8c0a757461fe66b2521965202a56.
v1.0.5 should work with Lua 5.3.
