### ISSUE TITLE
Is there something I can just drop onto a raspberry pi zero?

### ISSUE THREAD

**Issue by cinderblockgames** [vsergeev/lua-periphery#30]
I'm using a Keybow MINI on a raspberry pi zero w, which has a very stripped-down OS and is difficult to connect to.  You add files to it by just dropping them onto the sd card.  I want to add a passive buzzer, and this looks promising.  What's the best way to get something I can just drop onto the sd card and use from lua?

**Comment by vsergeev** [comment]
It'll probably be easiest to build it directly on the Pi. But, if lua is already installed on the Pi OS and you have a cross-compiler on your host computer, you could cross-compile ( https://github.com/vsergeev/lua-periphery?tab=readme-ov-file#cross-compiling-from-source ) lua-periphery and drop the `periphery.so` onto the SD Card. That should be enough to load it and use it.
