### ISSUE TITLE
Build fails on Sparc/Sparc64

### ISSUE THREAD

**Issue by tpetazzoni** [vsergeev/lua-periphery#7]
Hello,

I already reported this issue (and sent a patch to fix it on c-periphery), but it still affects version 1.0.6 of lua-periphery: the build fails on sparc due to certain high baudrates not being supported. See http://autobuild.buildroot.org/results/c2f/c2fd64ed2f17c53a4704284a8281305f97a48169/build-end.log for an example of build failure.

It is probably just a matter of updating the c-periphery submodule used by lua-periphery, and doing a new lua-periphery release. The c-periphery commit fixing the issue is https://github.com/vsergeev/c-periphery/commit/114c715c78ce300a5cd64fb71f32ffd2bce5326c.

Thanks!

**Comment by vsergeev** [comment]
Thanks -- finally got around to bumping this.
